version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: test-app-docker
    container_name: test-app-container
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html